#port no.
server:
  port: 8080
  
#in case of ip change ,it will help in detect eureka server
eureka:
  instance:
    hostname: localhost

#GateWay Configuration
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/user/**
          
        - id: CONTACT-SERVICE
          uri: lb://CONTACT-SERVICE
          predicates:
          - Path=/contact/**
        

  
   
    